### ISSUE TITLE
Ventura: can't boot to the install media (auto reboot after apple logo)

### ISSUE THREAD

**Issue by ghost** [valnoxy/t480-oc#128]
When I boot to the install media, the Apple logo shows up with a progress bar below it. The progress bar eventually fills up, and it briefly shows the background of the install environment, showing a mouse I can even move but then rebooting the computer.

I've already installed Ventura other times in this laptop, idk what's going on. It's the i5-8350U variant with 16GB of memory, a 256GB NVMe SSD, 1920x1080 display (no touch) and original Intel Wi-Fi/BT.

The failed boot:
https://www.youtube.com/watch?v=kzJGwcPttVY

**Comment by lmk2k5** [comment]
Hey,I am facing the same issue.Did you find a solution for it?

**Comment by ruyla** [comment]
Same issue here. Seems like the version a few months ago was working fine.

**Comment by seargentpepper** [comment]
I was facing something similar, in one attempt I installed in another drive (slow mechanical drive I had resting around my house) and then I clone the slow drive to the new SSD. I booted normally, also,  in my new Hack, I was having troubles to install, this time, I changed the view in the Drive partition manager, and I erased the drive instead erasing the volume.

**Comment by gabsteinbachz** [comment]
> I was facing something similar, in one attempt I installed in another drive (slow mechanical drive I had resting around my house) and then I clone the slow drive to the new SSD. I booted normally, also, in my new Hack, I was having troubles to install, this time, I changed the view in the Drive partition manager, and I erased the drive instead erasing the volume.

The problem is booting to the install media, so I can't even install to any other drive.

**Comment by seargentpepper** [comment]
> > I was facing something similar, in one attempt I installed in another drive (slow mechanical drive I had resting around my house) and then I clone the slow drive to the new SSD. I booted normally, also, in my new Hack, I was having troubles to install, this time, I changed the view in the Drive partition manager, and I erased the drive instead erasing the volume.
> 
> 
> 
> The problem is booting to the install media, so I can't even install to any other drive. 

Where dos you download and made your bootable USB? Did you used create media install?

**Comment by gabsteinbachz** [comment]
> Where dos you download and made your bootable USB? Did you used create media install?

I followed the guide in the repo's README.

**Comment by th1nhhdk** [comment]
I have the same problem

**Comment by th1nhhdk** [comment]
> I have the same problem with ~~Ventura~~
> 
> Edit: The macrecovery command in README.md is mislabeled, it downloads Sonoma, not Ventura
> To download Ventura: `python ./macrecovery.py -b Mac-4B682C642B45593E -m 00000000000000000 download`

I tried Ventura, same problem

In Sonoma the loading bar is on the bottom of the screen while Ventura is in the correct location

**Comment by valnoxy** [comment]
I have made a few changes in the dev branch. Does the problem still exist with this? https://github.com/valnoxy/t480-oc/tree/dev

**Comment by th1nhhdk** [comment]
> Oh wait, I have a unsupported NVME ssd (Micron 2200)

After swaping the nvme ssd for another one it boots like normal
using the latest release, not the `dev` branch

also, the `macrecovery` command for downloading macOS Ventura is wrong, it actually downloads macOS Sonoma instead
