### ISSUE TITLE
Love and Edits to be done on README.md

### ISSUE THREAD

**Issue by alex070609** [valnoxy/t480-oc#145]
Hi,

I Love your work thanks so much ! it's been really easy to setup this Hackintosh and i love the fact that you've called It "Thinkintosh" in your video this is brilliant <3

Two thing about your README.md

At line 95 : `<summary><strong>⚙️ Preperation</strong></summary>`
Small issue with the writing "Preparation" would be correct

and

At line 197 : `-  Thunderbolt BIOS Assist Mode: **UEFI Only**`
Thunderbolt BIOS Assist Mode should be "Disabled" else you cannot boot to the USB pen drive ;)

Other than that your guide is thorough and very clear, even for beginners ! Thanks a lot

Have a great day/night
Bacchus

**Comment by valnoxy** [comment]
Thanks! I have corrected the readme file.
