### ISSUE TITLE
No sonoma link for macrecovery

### ISSUE THREAD

**Issue by khlivnyi** [valnoxy/t480-oc#147]
In preparation chapter there is no Sonoma link for macrecovery download, but project description mention Sonoma as one of the main versions.
Can I just use the latest sonoma link in macrecovery list?

**Comment by EvoSpido** [comment]
The Ventura command downloads the recovery utility for macOS Sonoma... do not ask me why

**Comment by khlivnyi** [comment]
> The Ventura command downloads the recovery utility for macOS Sonoma... do not ask me why

Yep. I thought I was doing something wrong. By the chance, did you get Sonoma on your machine? The best I've got is fully working Monterey, but I want so badly to try Sonoma, but it boot loops after  I've done everything by the tutorial. Bootloop, after downloading all installation files, does not get to choose region selection

**Comment by khlivnyi** [comment]
> Nope, getting the same exact problem here. I found this command `python ./macrecovery.py -b Mac-4B682C642B45593E -m 00000000000000000 download` that seems to install macOS Ventura though, so I'm trying this next.

Good luck, 
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install-recovery.html

Has this listed as lastest Sonoma: 
python3 ./macrecovery.py -b Mac-937A206F2EE63C01 -m 00000000000000000 download

maybe it will work on your machine

**Comment by khlivnyi** [comment]
If someone boot looping after installing Sonoma, the solution is 
Disable Apple SecureBoot in your config.plist,
Misc->Security->SecureBootModel set as Disabled (case-sensitive)
Once 'Install macOS' entries are done doing the installation, the bug should have sorted itself out. And then you may set it back to Default
