### ISSUE TITLE
Update for macOS 15 Sequoia and further

### ISSUE THREAD

**Issue by qt2409xde** [valnoxy/t480-oc#153]
This EFI said that it's still maintained, I'm waiting for more updates but nope. It seems like you don't maintain this EFI anymore, there is a guy got stuck in a reboot loop on the second stage of setup due to some changes to Sonoma 14.4+. So, if you **still** maintain this EFI, please leave us an update, I'm waiting for the macOS Seqouia so much. Please, update this EFI if you can!

Thanks.

**Comment by Evanston09** [comment]
I am not the maintainer nor affiliated with him but to fix the reboot loop with Sonoma I had to change SecureBootModel in the config.plist to Disabled. Also if you check out the dev branch of this repo there are commits from around the time you posted this so I assume there is still development being done. Also try to use the dev branch with Sonoma. I could not get the wifi or bluetooth to work on the non-heliport version of the main release but it works perfectly with the dev branch.
