### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by Mifaxav** [valnoxy/t480-oc#18]
@valnoxy sorry for disturbing you again but, bluetooth keeps on crashing. In sys pref I get the notification saying: Could not load bluetooth preference pane and bluetooth doesn't work off the menu bar either. its probably a bug but can you try to get it fixed? Thanks :D

**Comment by Mifaxav** [comment]
lol...

**Comment by thishome** [comment]
I use airportlwm, and it work fine.
