### ISSUE TITLE
Keyboard identification

### ISSUE THREAD

**Issue by Andy-Man** [valnoxy/t480-oc#27]
AltGR is identified as left_option but must be right_option.

Thanks a lot

**Comment by WigHlod** [comment]
Same for me Azerty Keyboar here.

**Comment by ricardomaximojr** [comment]
@Andy-Man and @WigHlod , workaround by commenting line with "e038=e05b", in [SSDT-KBRD.dsl](https://github.com/valnoxy/t480-oc/blob/main/Source%20Code/SSDT-KBRD.dsl), saving as .aml using MaciASL, then replacing the one in the ACPI folder.

You may use the attached file. Unzip first.
[SSDT-KBRD.zip](https://github.com/valnoxy/t480-oc/files/9804029/SSDT-KBRD.zip)
