### ISSUE TITLE
Ventura issues on my T480

### ISSUE THREAD

**Issue by bjwil1991** [valnoxy/t480-oc#57]
I upgraded to Ventura after I copied the new files over to the EFI file system and I also copied the parameters in the config.plist file beforehand. After the install, three issues I run into are the following:

1) when the system boots up, whether a reboot or cold start, it'll say your system ran into a problem. Press any key to reboot or wait a few seconds. If I press any key or wait a few seconds, it boots up.

2) if I close the lid and re-open it to wake it up from sleep mode, it reboots. Even without the lid closed and if I let it sit for about 5-10 minutes of inactivity, it does the same thing.

3) Alongside Monterey, I cannot connect to any hidden network that I have for connecting to my Time Capsule boxes so I can backup the system entirely.

I never had these issues with Monterey 12.X (except the third one has been an issue anyway) and I cannot make heads or tails for this. Has anyone had this issue and how did you fix it?

**Comment by estevaorqto** [comment]
I had the same issue when I updated my Monterey to Ventura
I identified this kernel panic when I'm troubleshooting the problem on the Ventura:

```
panic(cpu 0 caller 0xffffff801cf4aee3): Kernel trap at 0xffffff801ce4ab71, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000042, CR3: 0x0000000026f62000, CR4: 0x00000000003626e0
RAX: 0xffffffa238a132e0, RBX: 0xffffff989e9e9c00, RCX: 0x0000000000000001, RDX: 0x0000000000000001
RSP: 0xffffff803eeffdd0, RBP: 0xffffff803eeffe00, RSI: 0xffffffa237718fe0, RDI: 0x0000000000000002
R8:  0x000000000000ffff, R9:  0x00000000ffffffff, R10: 0x0000000000000001, R11: 0x0000000000000080
R12: 0x0000000000000000, R13: 0xffffff93d2706970, R14: 0x0000000000000001, R15: 0x0000000000000002
RFL: 0x0000000000010202, RIP: 0xffffff801ce4ab71, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000042, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Panicked task 0xffffffa237dfa218: 192 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffffa7044c1598, Frame : Return Address
0xffffff803eeff7b0 : 0xffffff801cdedf9d 
0xffffff803eeff800 : 0xffffff801cf5b786 
0xffffff803eeff840 : 0xffffff801cf4aa10 
0xffffff803eeff890 : 0xffffff801cd88951 
0xffffff803eeff8b0 : 0xffffff801cdee27d 
0xffffff803eeff9a0 : 0xffffff801cded929 
0xffffff803eeffa00 : 0xffffff801d5e0ecb 
0xffffff803eeffaf0 : 0xffffff801cf4aee3 
0xffffff803eeffc70 : 0xffffff801cf4abd2 
0xffffff803eeffcc0 : 0xffffff801cd88951 
0xffffff803eeffce0 : 0xffffff801ce4ab71 
0xffffff803eeffe00 : 0xffffff801f4d9d22 
0xffffff803eeffe30 : 0xffffff801d4e4683 
0xffffff803eeffea0 : 0xffffff801d5134ae 
0xffffff803eeffee0 : 0xffffff801d4e38df 
0xffffff803eefff60 : 0xffffff801d4f0337 
0xffffff803eefffa0 : 0xffffff801cd8819e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOHIDFamily(2.0)[96D09D0F-DCBC-317F-A955-2BAAEB46FCFF]@0xffffff801f4cb000->0xffffff801f52bfff
            dependency: com.apple.iokit.IOReportFamily(47)[3115840D-90F4-383F-8991-D3CF8891C24C]@0xffffff801f840000->0xffffff801f842fff

Process name corresponding to current thread (0xffffffa7044c1598): kernel_task

Mac OS version:
22A400

Kernel version:
Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Kernel UUID: BF7C9676-EF23-3E8D-A2E2-25DAC63091B6
roots installed: 0
KernelCache slide: 0x000000001ca00000
KernelCache base:  0xffffff801cc00000
Kernel slide:      0x000000001cadc000
Kernel text base:  0xffffff801ccdc000
__HIB  text base: 0xffffff801cb00000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 3149710644395
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000002dd59625875
  Sleep   : 0x000002dd2e963d38 0x0000000a2de927f5 0x0000000000000000
  Wake    : 0x000002dd32212622 0x00000000539af4e6 0x000002dd2fe935f6
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 1 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8d6a572000 - 0xffffffad6a572000
  . PGZ   : 0xffffff8d6a572000 - 0xffffff8d6c573000
  . VM    : 0xffffff8d6c573000 - 0xffffff9238d72000
  . RO    : 0xffffff9238d72000 - 0xffffff93d2572000
  . GEN0  : 0xffffff93d2572000 - 0xffffff989ed72000
  . GEN1  : 0xffffff989ed72000 - 0xffffff9d6b572000
  . GEN2  : 0xffffff9d6b572000 - 0xffffffa237d72000
  . GEN3  : 0xffffffa237d72000 - 0xffffffa704572000
  . DATA  : 0xffffffa704572000 - 0xffffffad6a572000
  Metadata: 0xffffffffb986a000 - 0xffffffffd986a000
  Bitmaps : 0xffffffffd986a000 - 0xffffffffdf86a000
```

**Comment by estevaorqto** [comment]
The latest EFi in the repository is stable for me on Monterey

**Comment by bjwil1991** [comment]
panic(cpu 0 caller 0xffffff800654aee3): Kernel trap at 0xffffff800644ab71, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000042, CR3: 0x0000000010560000, CR4: 0x00000000003626e0
RAX: 0xffffff86d8a8bb30, RBX: 0xffffff953d600e00, RCX: 0x0000000000000001, RDX: 0x0000000000000001
RSP: 0xffffffad9eeb3dd0, RBP: 0xffffffad9eeb3e00, RSI: 0xffffff9a0965cfe0, RDI: 0x0000000000000002
R8:  0x000000000000ffff, R9:  0x00000000ffffffff, R10: 0x0000000000000001, R11: 0xffffff8ba1dc0350
R12: 0x0000000000000000, R13: 0xffffff8ba447a5b0, R14: 0x0000000000000001, R15: 0x0000000000000002
RFL: 0x0000000000010202, RIP: 0xffffff800644ab71, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000042, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Panicked task 0xffffff953d485218: 182 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffff9070af5598, Frame : Return Address
0xffffffad9eeb37b0 : 0xffffff80063edf9d 
0xffffffad9eeb3800 : 0xffffff800655b786 
0xffffffad9eeb3840 : 0xffffff800654aa10 
0xffffffad9eeb3890 : 0xffffff8006388951 
0xffffffad9eeb38b0 : 0xffffff80063ee27d 
0xffffffad9eeb39a0 : 0xffffff80063ed929 
0xffffffad9eeb3a00 : 0xffffff8006be0ecb 
0xffffffad9eeb3af0 : 0xffffff800654aee3 
0xffffffad9eeb3c70 : 0xffffff800654abd2 
0xffffffad9eeb3cc0 : 0xffffff8006388951 
0xffffffad9eeb3ce0 : 0xffffff800644ab71 
0xffffffad9eeb3e00 : 0xffffff8008ad9d22 
0xffffffad9eeb3e30 : 0xffffff8006ae4683 
0xffffffad9eeb3ea0 : 0xffffff8006b134ae 
0xffffffad9eeb3ee0 : 0xffffff8006ae38df 
0xffffffad9eeb3f60 : 0xffffff8006af0337 
0xffffffad9eeb3fa0 : 0xffffff800638819e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOHIDFamily(2.0)[96D09D0F-DCBC-317F-A955-2BAAEB46FCFF]@0xffffff8008acb000->0xffffff8008b2bfff
            dependency: com.apple.iokit.IOReportFamily(47)[3115840D-90F4-383F-8991-D3CF8891C24C]@0xffffff8008e40000->0xffffff8008e42fff

Process name corresponding to current thread (0xffffff9070af5598): kernel_task
Boot args: rtcfx_exclude=80-AB

Mac OS version:
22A400

Kernel version:
Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Kernel UUID: BF7C9676-EF23-3E8D-A2E2-25DAC63091B6
roots installed: 0
KernelCache slide: 0x0000000006000000
KernelCache base:  0xffffff8006200000
Kernel slide:      0x00000000060dc000
Kernel text base:  0xffffff80062dc000
__HIB  text base: 0xffffff8006100000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: YES
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 607735211152
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000008d7fd7691d
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000cba886b68 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff806fc1b000 - 0xffffffa06fc1b000
  . PGZ   : 0xffffff806fc1b000 - 0xffffff8071c1c000
  . VM    : 0xffffff8071c1c000 - 0xffffff853e41b000
  . RO    : 0xffffff853e41b000 - 0xffffff86d7c1b000
  . GEN0  : 0xffffff86d7c1b000 - 0xffffff8ba441b000
  . GEN1  : 0xffffff8ba441b000 - 0xffffff9070c1b000
  . GEN2  : 0xffffff9070c1b000 - 0xffffff953d41b000
  . GEN3  : 0xffffff953d41b000 - 0xffffff9a09c1b000
  . DATA  : 0xffffff9a09c1b000 - 0xffffffa06fc1b000
  Metadata: 0xffffffbaf8b83000 - 0xffffffbb18b83000
  Bitmaps : 0xffffffbb18b83000 - 0xffffffbb1eb83000

This is the kernel panic message I get.

**Comment by bjwil1991** [comment]
Update: I found the culprit(s). First and foremost, I disabled the auto power off, sleep, and hibernation timers entirely and I disabled the VooDooI2C and VooDooI2CHID kernel drivers as they were causing too many issues (touch screen drivers have bugs). I haven't had the system reboot OR kernel panic for now and I'll keep an eye on this for a few days.

**Comment by MeiDi1317** [comment]
for the network problem, try to reset nvram, works for me :)

**Comment by alessaba** [comment]
> Update: I found the culprit(s). First and foremost, I disabled the auto power off, sleep, and hibernation timers entirely and I disabled the VooDooI2C and VooDooI2CHID kernel drivers as they were causing too many issues (touch screen drivers have bugs). I haven't had the system reboot OR kernel panic for now and I'll keep an eye on this for a few days.

VoodooI2C has a known [problem]((https://github.com/VoodooI2C/VoodooI2C/issues/507) in Ventura with USB attached touchpads (the T480/T480s touchscreen is USB attached) that makes the system panic at reboot and also introduces sleep issues. so you did the right thing disabling it for now

**Comment by seargentpepper** [comment]
> Update: I found the culprit(s). First and foremost, I disabled the auto power off, sleep, and hibernation timers entirely and I disabled the VooDooI2C and VooDooI2CHID kernel drivers as they were causing too many issues (touch screen drivers have bugs). I haven't had the system reboot OR kernel panic for now and I'll keep an eye on this for a few days.

is this exclusive from Ventura or also happens in Mont?
