### ISSUE TITLE
Unable to find base image record in OpenCore menu

### ISSUE THREAD

**Issue by fabiandiez** [valnoxy/t480-oc#6]
Hi,

I am unable to find the base image record in the OpenCore menu.
After startup, I am only able to see a "Windows" options.

Using different EFI setups, I was able to boot into macOS earlier, but was trying to use this repo as it seems up-to-date and well maintained.

On my installation media, I created the `com.apple.recovery.boot ` containing the `BaseSystem.chunklist` as well as the `BaseSystem.dmg`. I also tried using both the Monterey and the HeliPad EFI configurations, but had no luck using either.

Any ideas why this might be happening? Any help would be appreciated.

Notes: 
I've formatted my USB drive using https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#rufus-method, as it is too big to be formatted by diskutil, but I am assuming this does not make a difference since it worked earlier with different EFI setups. 
I have used the macrecovery utility provided by OpenCore to option the base image, using `python macrecovery.py -b Mac-E43C1C25D4880AD6 -m 00000000000000000 download` (Monterey).

**Comment by valnoxy** [comment]
Hi,
You need to press the space bar in the OpenCore menu to see the drive.

**Comment by fabiandiez** [comment]
Hi, thanks for the quick response.
Was able to boot the image and perform a successful installation.
