### ISSUE TITLE
[Resolved] restart after reaching 11 minutes while installing.

### ISSUE THREAD

**Issue by AbuYousof26** [valnoxy/t480-oc#72]
I have the laptop but with I7 8650U after erasing the SSD then i continue to install but suddenly when i reach 11 minutes laptop getting restart and start over all things like tilling me to install the OS not attempting me for the new selection of Install MacOS as usual.

can anyone help, please note i tried with Big Sur, Monterey and Ventura all giving same then i tried to change the CPU model but it's not loading any more.
many thanks in advance.

**Comment by cchewanik** [comment]
during installation it does reboot a few times, you should see a menu option in your boot loader to continue with the installation? I don't quite understand your problem, can you explain it again?

**Comment by AbuYousof26** [comment]
Yes it should do that but it should appear a new option like "install MacOS" this not showing only showing "install macos monterey" and if click that it will return me back to first installation window the one it showing you Time machine, install macos monterey , safari and disk utility.

And keep looping till no time

**Comment by AbuYousof26** [comment]
any one can help pls

**Comment by cchewanik** [comment]
I presume your usb EFI is working since you can get it to boot to start the install. I had some issues with the stock Lenovo NVME, would cause random reboots or slowdowns. Does it always reboot at the same time or is it random? If you have an external hard drive try installing it there to rule out your nvme.

**Comment by AbuYousof26** [comment]
many thanks for your replay, yes i have i will test then i will update you, i like your idea 
 :)

**Comment by AbuYousof26** [comment]
great news, its works with my WD Passport external USB, i tried to clone the WD with NVMe but with no luck.
special thanks for you cchewanik and

**Comment by AbuYousof26** [comment]
Many thanks cchewanik
