### ISSUE TITLE
trackpad issues

### ISSUE THREAD

**Issue by Mifaxav** [valnoxy/t480-oc#8]
Its mostly fine but sometimes applications in the dock need to be double clicked to work. Plus, 3 finger tracking is not the best either. can you try to match it with EEtagent's one somehow? And this is for the master Monterey EFI. 

https://github.com/EETagent/T480-OpenCore-Hackintosh

**Comment by Mifaxav** [comment]
@valnoxy any ideas why this might be happening?

whenever I try to open an application on the dock(using my trackpad), it shows me a screen saying "No available windows"

The tracking using my trackpad is not the best either if compared to EETagent's one (refi link above)

currently using the master 'EFI Monterey' with macOS Monterey and working on a fix myself :D

**Comment by valnoxy** [comment]
Hey, thanks for your feedback!
This issue should be patched now. If you still have issues, feel free to reach out!
