### ISSUE TITLE
Is not a Issue, enable BCM94360NG 

### ISSUE THREAD

**Issue by gilberth** [valnoxy/t480-oc#82]
I bought a BCM94360NG card, but i can't enable airDrop.

**Comment by gilberth** [comment]
Disable Airportbrcmfixup, Bluetoolfixup, Brcmfirmwaredata, Brcmpatchram3

**Comment by Mifaxav** [comment]
Any idea about the BCM94352Z?? im only getting airdrop, wifi and bt. No continuity or handoff :(
